### ISSUE TITLE
Check and refresh session

### ISSUE THREAD

**Issue by roydigerhund** [sergiodxa/remix-auth-form#22]
With the current solution an user is authenticated as long as a valid session cookie is provided. What I miss is a `checkSession` function like in [remix-auth-supabase](https://github.com/mitchelvanbever/remix-auth-supabase) to validate the user against the database while he still has a valid session cookie. When `checkSession` is called successfully we can also set the session cookie again to keep the user logged in. 

How do you like the idea? I would be open to help with the implementation.

**Comment by sergiodxa** [comment]
This is outside the scope of the strategy whose only focus is provide a way to use Remix Auth with a form to authenticate the user.

This is something that could be built directly in the app, and most likely make sense since it depends on your database.

The Supabase strategy had to add these methods because of how Supabase works.
