### ISSUE TITLE
Add support for "remember" option.

### ISSUE THREAD

**Issue by revickulous2001** [sergiodxa/remix-auth-form#34]
I don't see any way to add the ability for a user to check a "remember me" box on the form to set the maxAge value of the session to something like 30 days.

In Remix-land, this would be done with a session commit like this:

```
await sessionStorage.commitSession(session, {
  maxAge: remember
    ? 60 * 60 * 24 * 7 // 7 days
    : undefined,
}),
```

But Remix-Auth doesn't seem to have a way to provide an "options" object that can be passed to the commitSession call.

**Comment by sergiodxa** [comment]
If you don't add the successRedirect to the `authenticate` method it will return the user data instead of setting it in the session, then you can add it yourself to the session and commit the session with any cookie maxAge value.

See https://github.com/sergiodxa/remix-auth#custom-redirect-url-based-on-the-user for a similar example (this one don't add successRedirect to customize the redirect URL but it has to call the commitSession).
