### ISSUE TITLE
The FormStrategy constructor doesn't accept any arguments.

### ISSUE THREAD

**Issue by Artmann** [sergiodxa/remix-auth-form#37]
It looks like the constructor is broken in the `v1.5.0` version. 

**Expected 0 arguments, but got 1.ts(2554)** 

![image](https://github.com/sergiodxa/remix-auth-form/assets/91954/91b87fb6-4aa6-4540-b8b4-94d198b3e6ec)

The constructor seems to be missing in `index..d.ts`

```
import { AppLoadContext, SessionStorage } from "@remix-run/server-runtime";
import { AuthenticateOptions, Strategy } from "remix-auth";
export interface FormStrategyVerifyParams {
    /**
     * A FormData object with the content of the form used to trigger the
     * authentication.
     *
     * Here you can read any input value using the FormData API.
     */
    form: FormData;
    /**
     * An object of arbitrary for route loaders and actions provided by the
     * server's `getLoadContext()` function.
     */
    context?: AppLoadContext;
    /**
     * The request that triggered the authentication.
     */
    request: Request;
}
export declare class FormStrategy<User> extends Strategy<User, FormStrategyVerifyParams> {
    name: string;
    authenticate(request: Request, sessionStorage: SessionStorage, options: AuthenticateOptions): Promise<User>;
    private readFormData;
}

```

**Comment by sergiodxa** [comment]
The constructor is not needed because FormStrategy uses the same one used by Strategy class from Remix Auth, that's why it's not in the type.

The tests of the packages shows TS doesn't complain against the constructor argument, even when importing from the built files instead of the source files.

If you can, try to create a reproduction repo with this TS issue.
